---
- name: API_KEY
  type: text
  required: true
- name: API_SECRET
  type: text
  required: true
- name: DB_HOST
  type: text
- name: DB_PORT
  type: integer
- name: DB_NAME
  type: text
- name: DB_USER
  type: text
